### ISSUE TITLE
pb on reloading same page

### ISSUE THREAD

**Issue by iNeoO** [nuxt-modules/leaflet#49]
Hi got a problem with the integration of the module

got a pb on this repo

https://github.com/SocialGouv/vao

```
Unhandled error during execution of unmounted hook 
  at <Anonymous url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution="&copy; <a href=\"https://www.openstreetmap.org/\">OpenStreetMap</a> contributors" layer-type="base"  ... > 
  at <Anonymous ref="map" zoom=16 center= (2) [48.533089, 7.772417]  ... > 
  at <DsfrFieldset legend="Informations sur le lieu de l'hébergement" > 
  at <Hebergement init-hebergement= {nom: 'coucou', dateFin: '2024-07-31T22:00:00.000Z', dateDebut: '2024-07-23T22:00:00.000Z', coordonnees: {…}, hebergementId: 1, …} is-disabled="" cdn-url="http://localhost:3010/documents/"  ... > 
  at <[hebergementId] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <Anonymous key="/hebergements/pour-sejour()/4()/1()" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/hebergements/pour-sejour/4/1', path: '/hebergements/pour-sejour/4/1', query: {…}, hash: '', name: 'hebergements-type-demandeSejourId-hebergementId', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Default ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <LayoutLoader key="default" layoutProps= {ref: RefImpl} name="default" > 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=4 > 
  at <NuxtRoot>
 ```
 
 ```
 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for '_leaflet_id' in undefined
    at stamp (leaflet-src.esm-IDLFMH26.js?v=a5d52f79:35:23)
    at NewClass.removeLayer (leaflet-src.esm-IDLFMH26.js?v=a5d52f79:4475:14)
    at RefImpl.removeLayer (@vue-leaflet_vue-leaflet.js?v=a5d52f79:1419:29)
    at t (@vue-leaflet_vue-leaflet.js?v=a5d52f79:66:22)
    at u (@vue-leaflet_vue-leaflet.js?v=a5d52f79:169:57)
    at @vue-leaflet_vue-leaflet.js?v=a5d52f79:212:41
    at runtime-core.esm-bundler.js?v=a5d52f79:1804:40
    at callWithErrorHandling (runtime-core.esm-bundler.js?v=a5d52f79:193:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?v=a5d52f79:200:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js?v=a5d52f79:1784:19)
``` 

With https://github.com/SocialGouv/vao/blob/feat/502/packages/frontend-bo/src/pages/hebergements/%5Btype%5D/%5BhebergementId%5D.vue 

or https://github.com/SocialGouv/vao/blob/feat/502/packages/frontend-bo/src/pages/hebergements/%5Btype%5D/%5BdemandeSejourId%5D/%5BhebergementId%5D.vue

Switching between these page and going back on the same page create this problem
 
![6b4ef54f-97cb-404b-a2c7-bcd2c8294aa1](https://github.com/user-attachments/assets/d71e0e26-f1aa-46b2-892f-819a7e8df751)

Maybe i'm doing wrong, any idea why the unmounted is wrongly executed ?

**Comment by Gugustinette** [comment]
Hi !

I tried to get every info so you can better understand the error, where it comes from, and how to fix it :

## Debugging info

### Leaflet side

The error seems to be thrown from [Leaflet](https://github.com/Leaflet/Leaflet/tree/93f681c488ec07690cd4a393056078cf88f3bcff) in [Layer.removeLayer](https://github.com/Leaflet/Leaflet/blob/93f681c488ec07690cd4a393056078cf88f3bcff/src/layer/Layer.js#L179-L198) by [Util.stamp](https://github.com/Leaflet/Leaflet/blob/93f681c488ec07690cd4a393056078cf88f3bcff/src/core/Util.js#L27-L34) (Layer is a class extended by [Marker](https://github.com/Leaflet/Leaflet/blob/93f681c488ec07690cd4a393056078cf88f3bcff/src/layer/marker/Marker.js#L23)).

[This line](https://github.com/Leaflet/Leaflet/blob/93f681c488ec07690cd4a393056078cf88f3bcff/src/core/Util.js#L30) seems to throw an error because the object given is undefined.

### Vue Leaflet side

[Vue Leaflet](https://github.com/vue-leaflet/vue-leaflet) runs some code when a component is unmounted, including [this line](https://github.com/vue-leaflet/vue-leaflet/blob/db34dff79cc62bc6fa51357e953e9bcf55725c94/src/functions/layer.ts#L150) which call [removeThisLayer](https://github.com/vue-leaflet/vue-leaflet/blob/db34dff79cc62bc6fa51357e953e9bcf55725c94/src/functions/layer.ts#L57-L58). This is a function defined on component setup, in our case [here for LMarker](https://github.com/vue-leaflet/vue-leaflet/blob/db34dff79cc62bc6fa51357e953e9bcf55725c94/src/components/LMarker.vue#L66).
This means the [leafletObject ref](https://github.com/vue-leaflet/vue-leaflet/blob/db34dff79cc62bc6fa51357e953e9bcf55725c94/src/components/LMarker.vue#L44) from LMarker gives a `.value` of undefined when unmounting the component.

This seems related to https://github.com/vue-leaflet/vue-leaflet/issues/52 which mention the onUnmounted code being called twice for some reason.

## Fix

From what I understand of your codebase, code such as [the inline map here](https://github.com/SocialGouv/vao/blob/5e6539f6179934a9308159a98e4811f5b240a21e/packages/frontend-usagers/src/components/hebergement.vue#L43-L64) or [slotted map here](https://github.com/SocialGouv/vao/blob/feat/502/packages/shared/src/components/Hebergement.vue#L46-L53) are using `v-if` to show the map only if an address is defined.
As mentioned [here](https://github.com/vue-leaflet/vue-leaflet/issues/52#issuecomment-727292992), potential fixes you could try are : using `v-show`, moving the statements directly to childrens ...

**Comment by iNeoO** [comment]
Ok i find a way with some v-show, thx

**Comment by iNeoO** [comment]
In fact removing all v-if v-show doesn´t fix the problem :/

**Comment by iNeoO** [comment]
removeLayer is called with no params at the loading creating the error

**Comment by Gugustinette** [comment]
Could also be related to https://github.com/vue-leaflet/vue-leaflet/issues/340

Definitely an issue from Vue Leaflet, so I guess it should be opened on [Vue Leaflet repo](https://github.com/vue-leaflet/vue-leaflet).
As Vue Leaflet development seems "paused" (no release for a year) I'll see if I can get my hands on it to help fixing it.

**Comment by iNeoO** [comment]
For the moment i will just hide component on pages with trouble to merge my branch I would be very interested if a solution is found.

**Comment by Gugustinette** [comment]
If no solution can be found in decent times, maybe it's also worth trying https://gugustinette.github.io/nuxt-maplibre/
which could work better.

They also support markers : https://indoorequal.github.io/vue-maplibre-gl/examples/marker.html

**Comment by iNeoO** [comment]
Ah really thx, maybe we will give a try to this, i will talk about it with other ppl Thx !

**Comment by mdavo6** [comment]
@iNeoO I ran into a similar problem today when navigating from one route to another (both which contained LMap components). The simplest solution for me was to add a key to the map object which changes depending on the data loaded. For me it made sense to use the project ID as the key, but could be anything related to the data being loaded. I assume this allows Vue to correctly identify and unmount the map object from the DOM.

For example
```
<LMap>
</LMap>
```
Would become
```
<LMap :key="project.id">
 </LMap>
```
I hope this helps you, and others in the future.
